{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccr.secretName" . }}
  labels:
    {{- include "ccr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.flask.secrets.secretKey }}
  SECRET_KEY: {{ .Values.flask.secrets.secretKey }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.flask.secrets.jwtSecretKey }}
  JWT_SECRET_KEY: {{ .Values.flask.secrets.jwtSecretKey }}
  {{- else }}
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.flask.secrets.jwtAdminKey }}
  JWT_ADMIN_KEY: {{ .Values.flask.secrets.jwtAdminKey }}
  {{- else }}
  JWT_ADMIN_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
