apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: ccr
    component: flask
spec:
  type: NodePort
  selector:
    app: ccr
    component: flask
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
  sessionAffinity: None
